[versions]
asciidoctor = "4.0.5"
boot-conditionals = "6.0.7"
commons-pool2 = "2.13.1"
confluent = "8.3.1"
contract-pdl-avro = "18"
cyclonedx = "3.4.1"
kotlin = "2.4.0"
kotest = "6.2.3"
logstash = "9.0"
logbook = "4.1.0"
mock-oauth2-server = "6.0.0"
opentelemetry = "2.30.0"
opentelemetry-alpha = "2.30.0-alpha"
slack-api = "1.49.0"
spring-boot = "4.1.1"
spring-dependency-management = "1.1.7"
springdoc = "3.1.0"
springmockk = "5.0.1"
testcontainers = "2.0.5"

[libraries]
boot-conditionals = { module = "no.nav.boot:boot-conditionals", version.ref = "boot-conditionals" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine" }
commons-pool2 = { module = "org.apache.commons:commons-pool2", version.ref = "commons-pool2" }
confluent-kafka-avro-serializer = { module = "io.confluent:kafka-avro-serializer", version.ref = "confluent" }
contract-pdl-avro = { module = "no.nav.pdl.libs:contract-pdl-avro", version.ref = "contract-pdl-avro" }
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }
hibernate-micrometer = { module = "org.hibernate.orm:hibernate-micrometer" }
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-bom = { module = "io.kotest:kotest-bom", version.ref = "kotest" }
kotest-extensions-spring = { module = "io.kotest:kotest-extensions-spring", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
logstash-logback-encoder = { module = "net.logstash.logback:logstash-logback-encoder", version.ref = "logstash" }
logbook-spring-boot-starter = { module = "org.zalando:logbook-spring-boot-starter", version.ref = "logbook" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus" }
opentelemetry-instrumentation-annotations = { module = "io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations" }
opentelemetry-instrumentation-bom = { module = "io.opentelemetry.instrumentation:opentelemetry-instrumentation-bom", version.ref = "opentelemetry" }
opentelemetry-logback-mdc = { module = "io.opentelemetry.instrumentation:opentelemetry-logback-mdc-1.0", version.ref = "opentelemetry-alpha" }
postgresql = { module = "org.postgresql:postgresql" }
slack = { module = "com.slack.api:slack-api-client-kotlin-extension", version.ref = "slack-api" }
spring-boot-micrometer-metrics-test = { module = "org.springframework.boot:spring-boot-micrometer-metrics-test" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-cache = { module = "org.springframework.boot:spring-boot-starter-cache" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-data-jpa-test = { module = "org.springframework.boot:spring-boot-starter-data-jpa-test" }
spring-boot-starter-data-redis = { module = "org.springframework.boot:spring-boot-starter-data-redis" }
spring-boot-starter-data-redis-test = { module = "org.springframework.boot:spring-boot-starter-data-redis-test" }
spring-boot-starter-flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
spring-boot-starter-graphql = { module = "org.springframework.boot:spring-boot-starter-graphql" }
spring-boot-starter-jetty = { module = "org.springframework.boot:spring-boot-starter-jetty" }
spring-boot-starter-kafka = { module = "org.springframework.boot:spring-boot-starter-kafka" }
spring-boot-starter-kafka-test = { module = "org.springframework.boot:spring-boot-starter-kafka-test" }
spring-boot-starter-mustache = { module = "org.springframework.boot:spring-boot-starter-mustache" }
spring-boot-starter-oauth2-client = { module = "org.springframework.boot:spring-boot-starter-oauth2-client" }
spring-boot-starter-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server" }
spring-boot-restclient = { module = "org.springframework.boot:spring-boot-restclient" }
spring-boot-starter-restclient-test = { module = "org.springframework.boot:spring-boot-starter-restclient-test" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-webclient = { module = "org.springframework.boot:spring-boot-starter-webclient" }
spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }
mock-oauth2-server = { module = "no.nav.security:mock-oauth2-server", version.ref = "mock-oauth2-server" }
spring-restdocs-mockmvc = { module = "org.springframework.restdocs:spring-restdocs-mockmvc" }
springdoc-openapi-webmvc-ui = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springdoc" }
springmockk = { module = "com.ninja-squad:springmockk", version.ref = "springmockk" }
testcontainers-bom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql" }
testcontainers-redis = { module = "com.redis:testcontainers-redis" }

[bundles]
kotest = ["kotest-runner-junit5", "kotest-assertions-core", "kotest-extensions-spring"]
observability = ["opentelemetry-instrumentation-annotations", "opentelemetry-logback-mdc", "micrometer-registry-prometheus"]

[plugins]
asciidoctor = { id = "org.asciidoctor.jvm.convert", version.ref = "asciidoctor" }
cyclonedx = { id = "org.cyclonedx.bom", version.ref = "cyclonedx" }
kotest = { id = "io.kotest", version.ref = "kotest" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }